// Original TOEIC-style practice questions generated for this trainer. These are not official TOEIC items.
window.TOEIC_PART5_QUESTIONS = [
    q("p5-001", "The marketing team will release the updated brochure as soon as the final design _____ approved.", ["is", "are", "was", "be"], 0, "주어가 the final design으로 단수이고, 시간 부사절에서는 미래 의미에도 현재시제를 씁니다.", "시제", "중급"),
    q("p5-002", "Applicants must submit the completed form _____ Friday to be considered for the internship.", ["until", "by", "during", "within"], 1, "마감 시점을 나타낼 때는 by를 씁니다. until은 상태가 계속되는 종료 시점에 어울립니다.", "전치사", "초급"),
    q("p5-003", "The new accounting software allows employees to process expense reports more _____.", ["efficient", "efficiency", "efficiently", "efficientness"], 2, "동사 process를 수식해야 하므로 부사 efficiently가 필요합니다.", "품사", "초급"),
    q("p5-004", "Because the conference room was already occupied, the interview was moved to _____ location.", ["another", "others", "each", "many"], 0, "단수 명사 location 앞에서 또 다른 하나를 뜻할 때 another를 씁니다.", "한정사", "중급"),
    q("p5-005", "The manager asked that all safety equipment _____ inspected before the facility opens.", ["is", "are", "be", "being"], 2, "ask that 절에서 요구를 나타낼 때 동사원형을 쓰며, 수동 의미라 be inspected가 맞습니다.", "가정법 현재", "고급"),
    q("p5-006", "Several customers complained that the online checkout process was _____ than expected.", ["complicated", "more complicated", "most complicated", "complicate"], 1, "than expected가 있으므로 비교급 more complicated가 필요합니다.", "비교급", "초급"),
    q("p5-007", "The shipment was delayed _____ severe weather conditions near the port.", ["because", "due to", "although", "despite of"], 1, "뒤에 명사구가 오므로 due to가 적절합니다. because 뒤에는 절이 와야 합니다.", "전치사구", "중급"),
    q("p5-008", "Ms. Han is responsible for reviewing contracts and _____ with outside legal counsel.", ["coordinate", "coordinated", "coordinating", "coordination"], 2, "for 뒤에서 reviewing과 병렬이 되어야 하므로 동명사 coordinating이 맞습니다.", "병렬 구조", "중급"),
    q("p5-009", "The restaurant has gained a reputation for serving meals made with _____ sourced ingredients.", ["local", "locally", "locality", "locate"], 1, "sourced라는 과거분사를 수식해야 하므로 부사 locally가 필요합니다.", "품사", "중급"),
    q("p5-010", "Neither the printer nor the scanner _____ functioning properly after the power outage.", ["were", "are", "is", "have"], 2, "neither A nor B에서는 가까운 주어 B에 수를 맞춥니다. scanner가 단수이므로 is가 맞습니다.", "수일치", "고급"),
    q("p5-011", "The training manual explains how to operate the machine _____ and effectively.", ["safe", "safely", "safety", "safer"], 1, "operate를 수식하고 effectively와 병렬을 이루므로 부사 safely가 필요합니다.", "품사", "초급"),
    q("p5-012", "The company will reimburse employees for travel expenses _____ they provide valid receipts.", ["as long as", "even though", "so that", "in case of"], 0, "유효한 영수증 제출이라는 조건을 나타내므로 as long as가 자연스럽습니다.", "접속사", "중급"),
    q("p5-013", "All participants are encouraged to arrive at least ten minutes _____ the workshop begins.", ["before", "between", "inside", "without"], 0, "워크숍 시작보다 앞선 시점을 나타내므로 before가 정답입니다.", "전치사", "초급"),
    q("p5-014", "The customer service department received _____ calls on Monday than on any other day last week.", ["many", "much", "more", "most"], 2, "than이 있으므로 비교급 more가 필요합니다.", "비교급", "초급"),
    q("p5-015", "The board members expressed their _____ for the revised budget proposal.", ["approve", "approved", "approval", "approving"], 2, "소유격 their 뒤에는 명사가 와야 하므로 approval이 맞습니다.", "품사", "초급"),
    q("p5-016", "The technician found the instructions difficult to follow because they were written _____.", ["unclear", "unclearly", "unclearness", "uncleared"], 1, "were written이라는 동사구를 수식해야 하므로 부사 unclearly가 필요합니다.", "품사", "중급"),
    q("p5-017", "_____ the renovation was completed on schedule, some employees requested additional lighting.", ["After", "Despite", "Although", "Because of"], 2, "뒤에 완전한 절이 오고 양보 의미가 필요하므로 Although가 맞습니다.", "접속사", "중급"),
    q("p5-018", "Expense reports must be submitted _____ than Friday noon to be included in this month's payroll.", ["later", "no later", "least", "soon"], 1, "마감 시한을 나타내는 표현은 no later than입니다.", "숙어 표현", "중급"),
    q("p5-019", "The contract will become valid once it _____ by both parties.", ["signs", "signed", "is signed", "will sign"], 2, "계약서는 서명되는 대상이므로 수동태 is signed가 필요합니다.", "태", "중급"),
    q("p5-020", "The online portal was designed to make registration _____ for first-time users.", ["easy", "easier", "easily", "ease"], 1, "기존보다 더 쉽게 만든다는 의미이므로 비교급 easier가 자연스럽습니다.", "비교급", "중급"),
    q("p5-021", "Mr. Ortiz has been in charge of supplier relations _____ 2022.", ["for", "since", "during", "by"], 1, "시작 시점 2022를 기준으로 현재까지 이어지는 기간은 since를 씁니다.", "전치사", "초급"),
    q("p5-022", "The instructions should be read _____ before the equipment is operated.", ["careful", "carefully", "care", "caring"], 1, "동사구 should be read를 수식하므로 부사 carefully가 맞습니다.", "품사", "초급"),
    q("p5-023", "A detailed summary of the survey results _____ included in the appendix.", ["are", "were", "is", "have"], 2, "핵심 주어는 summary로 단수이므로 is가 필요합니다.", "수일치", "중급"),
    q("p5-024", "The company postponed the seminar _____ low enrollment.", ["because", "because of", "although", "so that"], 1, "뒤에 명사구 low enrollment가 있으므로 because of가 맞습니다.", "전치사구", "초급"),
    q("p5-025", "The brochure contains information about services _____ are available to corporate clients.", ["who", "that", "where", "what"], 1, "선행사 services를 수식하는 주격 관계대명사 that이 필요합니다.", "관계사", "중급"),
    q("p5-026", "Employees are advised to keep their passwords _____.", ["confident", "confidential", "confidentially", "confidence"], 1, "keep 목적어 보어 구조에서 passwords의 상태를 설명하는 형용사 confidential이 맞습니다.", "어휘", "중급"),
    q("p5-027", "The new branch is located _____ walking distance of the train station.", ["within", "among", "onto", "beneath"], 0, "within walking distance는 걸어서 갈 수 있는 거리라는 고정 표현입니다.", "전치사", "중급"),
    q("p5-028", "The CEO thanked the team for completing the project ahead of _____.", ["schedule", "scheduled", "scheduling", "scheduler"], 0, "ahead of schedule은 예정보다 빨리라는 TOEIC 빈출 표현입니다.", "숙어 표현", "초급"),
    q("p5-029", "The warehouse manager made sure that each item _____ labeled before shipment.", ["was", "were", "be", "have"], 0, "each item은 단수이며 라벨이 붙여지는 대상이므로 was labeled가 맞습니다.", "수일치", "중급"),
    q("p5-030", "Applicants with international experience are especially encouraged _____.", ["apply", "to apply", "applying", "applied"], 1, "be encouraged to do 구조이므로 to apply가 정답입니다.", "부정사", "초급"),
    q("p5-031", "The software update will install automatically _____ the computer is restarted.", ["after", "despite", "therefore", "during"], 0, "뒤에 절이 오고 시간 관계를 나타내므로 after가 적절합니다.", "접속사", "초급"),
    q("p5-032", "The accounting team found several errors while _____ the quarterly report.", ["review", "reviewed", "reviewing", "reviews"], 2, "while 뒤에서 생략된 주어와 be동사를 고려하면 while reviewing이 자연스럽습니다.", "분사 구문", "중급"),
    q("p5-033", "The supervisor distributed the revised schedule to _____ employee.", ["all", "every", "many", "several"], 1, "단수 명사 employee 앞에는 every를 씁니다. all, many, several 뒤에는 복수 명사가 옵니다.", "한정사", "초급"),
    q("p5-034", "Tickets are available online and at the box office, _____ supplies last.", ["while", "whether", "unless", "because of"], 0, "while supplies last는 재고가 남아 있는 동안이라는 고정 표현입니다.", "접속사", "중급"),
    q("p5-035", "Our technical support staff can respond to inquiries more _____.", ["prompt", "promptness", "promptly", "prompter"], 2, "respond를 수식해야 하므로 부사 promptly가 필요합니다.", "품사", "초급"),
    q("p5-036", "The proposal was rejected because it lacked _____ financial projections.", ["accurate", "accuracy", "accurately", "accurateness"], 0, "명사 projections를 수식하므로 형용사 accurate가 맞습니다.", "품사", "초급"),
    q("p5-037", "The consultant recommended _____ the product launch until market research was complete.", ["delay", "delaying", "delayed", "to delay"], 1, "recommend는 목적어로 동명사를 자주 취하므로 delaying이 맞습니다.", "동명사", "고급"),
    q("p5-038", "The restaurant is looking for cooks who can work _____ with others.", ["cooperative", "cooperatively", "cooperation", "cooperate"], 1, "work를 수식해야 하므로 부사 cooperatively가 필요합니다.", "품사", "중급"),
    q("p5-039", "The new policy applies to all employees, _____ of department.", ["regardless", "regarding", "regarded", "regards"], 0, "regardless of는 관계없이를 뜻하는 고정 표현입니다.", "전치사구", "중급"),
    q("p5-040", "The printer has been repaired and is now _____.", ["operation", "operational", "operates", "operatively"], 1, "be동사 뒤 보어 자리에는 형용사 operational이 적절합니다.", "어휘", "초급"),
    q("p5-041", "The training session covers both customer service skills and conflict _____.", ["resolve", "resolving", "resolution", "resolved"], 2, "customer service skills와 병렬로 명사구가 필요하므로 conflict resolution이 맞습니다.", "어휘", "중급"),
    q("p5-042", "The hotel offers complimentary shuttle service _____ the airport and the downtown office.", ["between", "among", "during", "over"], 0, "두 지점 사이의 이동은 between A and B로 표현합니다.", "전치사", "초급"),
    q("p5-043", "We regret _____ you that the position has already been filled.", ["inform", "to inform", "informing", "informed"], 1, "regret to inform은 유감스럽게 알리다는 공식 문서 표현입니다.", "부정사", "중급"),
    q("p5-044", "The report must be submitted in the format _____ by the client.", ["specifies", "specifying", "specified", "specification"], 2, "format이 client에 의해 지정된 것이므로 과거분사 specified가 맞습니다.", "분사", "중급"),
    q("p5-045", "The shipment arrived _____ than the purchasing department expected.", ["early", "earliest", "earlier", "earliness"], 2, "than이 있으므로 비교급 earlier가 필요합니다.", "비교급", "초급"),
    q("p5-046", "The new benefits package is intended to improve employee _____.", ["retain", "retention", "retained", "retentive"], 1, "improve의 목적어 자리에는 명사 retention이 필요합니다.", "어휘", "중급"),
    q("p5-047", "The assembly line was shut down temporarily _____ a safety inspection could be performed.", ["so that", "because of", "despite", "whereas"], 0, "검사가 수행될 수 있도록이라는 목적을 나타내므로 so that이 맞습니다.", "접속사", "중급"),
    q("p5-048", "The survey was designed to measure customer _____ with the delivery service.", ["satisfy", "satisfied", "satisfaction", "satisfactorily"], 2, "measure의 목적어로 명사 satisfaction이 필요합니다.", "품사", "초급"),
    q("p5-049", "Please contact the front desk if you require _____ assistance.", ["further", "farther", "farthest", "furthestly"], 0, "추가적인 assistance라는 의미이므로 further가 자연스럽습니다.", "어휘", "중급"),
    q("p5-050", "The committee will review all applications before _____ a final decision.", ["make", "made", "making", "to make"], 2, "전치사 before 뒤에는 동명사 making이 옵니다.", "동명사", "초급"),
    q("p5-051", "The company has opened a facility _____ produces eco-friendly packaging.", ["who", "that", "where", "whose"], 1, "선행사 facility가 주어 역할을 하며 뒤 절을 이끄므로 that이 적절합니다.", "관계사", "중급"),
    q("p5-052", "The updated catalog is _____ available on the company website.", ["current", "currently", "currency", "currents"], 1, "available을 수식해 현재 이용 가능하다는 의미를 만들려면 부사 currently가 필요합니다.", "품사", "초급"),
    q("p5-053", "All invoices should be sent directly to the _____ department.", ["account", "accounting", "accounted", "accountable"], 1, "부서명을 나타내는 accounting department가 자연스러운 명사 수식 표현입니다.", "어휘", "초급"),
    q("p5-054", "Visitors must wear identification badges _____ on company premises.", ["while", "during", "because of", "despite"], 0, "회사 구내에 있는 동안이라는 시간 의미로 while이 자연스럽습니다.", "접속사", "중급"),
    q("p5-055", "The marketing assistant prepared a _____ list of media contacts.", ["comprehensive", "comprehend", "comprehensively", "comprehension"], 0, "명사 list를 수식하는 형용사 comprehensive이 맞습니다.", "어휘", "중급"),
    q("p5-056", "The director requested that the figures _____ checked again.", ["are", "were", "be", "being"], 2, "request that 절에서는 동사원형을 쓰며 수동 의미라 be checked가 맞습니다.", "가정법 현재", "고급"),
    q("p5-057", "The merger is expected to increase the firm's _____ in overseas markets.", ["present", "presence", "presently", "presentation"], 1, "시장에서의 입지를 뜻하는 명사 presence가 필요합니다.", "어휘", "중급"),
    q("p5-058", "The repair technician arrived shortly _____ the store opened.", ["after", "through", "among", "toward"], 0, "상점이 문을 연 직후 도착했다는 시간 관계이므로 after가 맞습니다.", "전치사", "초급"),
    q("p5-059", "The software is compatible _____ most operating systems.", ["to", "with", "for", "about"], 1, "compatible with는 와 호환되는이라는 고정 표현입니다.", "전치사", "초급"),
    q("p5-060", "Only employees _____ have completed the training may operate the equipment.", ["who", "which", "whose", "whom"], 0, "사람을 선행사로 하고 주어 역할을 하므로 who가 맞습니다.", "관계사", "중급"),
    q("p5-061", "The company chose a supplier known for its _____ delivery service.", ["rely", "reliable", "reliably", "reliability"], 1, "delivery service를 수식하는 형용사 reliable이 필요합니다.", "어휘", "초급"),
    q("p5-062", "Sales increased _____ after the advertising campaign began.", ["significant", "significance", "significantly", "signify"], 2, "increased를 수식해야 하므로 부사 significantly가 필요합니다.", "품사", "초급"),
    q("p5-063", "The building's main entrance will remain closed _____ further notice.", ["until", "by", "within", "throughout"], 0, "추후 공지가 있을 때까지라는 의미는 until further notice입니다.", "전치사", "중급"),
    q("p5-064", "The team worked late to ensure that the proposal was completed _____.", ["on time", "in time of", "at time", "by timely"], 0, "기한에 맞게라는 의미의 고정 표현은 on time입니다.", "숙어 표현", "초급"),
    q("p5-065", "Customers may exchange items _____ they have the original receipt.", ["although", "provided that", "so that", "because of"], 1, "원래 영수증이 있다는 조건을 나타내므로 provided that이 맞습니다.", "접속사", "고급"),
    q("p5-066", "The instruction manual was translated into three languages for the _____ of overseas staff.", ["convenient", "convenience", "conveniently", "convene"], 1, "for the convenience of는 의 편의를 위해라는 표현입니다.", "어휘", "중급"),
    q("p5-067", "The position requires someone who is highly _____ and detail-oriented.", ["organize", "organized", "organization", "organizing"], 1, "be동사 뒤에서 사람의 성향을 설명하는 형용사 organized가 필요합니다.", "어휘", "초급"),
    q("p5-068", "The maintenance crew checks the elevators _____ to prevent service interruptions.", ["regular", "regularly", "regularity", "regulate"], 1, "checks를 수식해야 하므로 부사 regularly가 맞습니다.", "품사", "초급"),
    q("p5-069", "The budget proposal includes a _____ of projected expenses.", ["breakdown", "break", "broken", "breaking"], 0, "비용 항목의 세부 내역은 a breakdown of expenses라고 표현합니다.", "어휘", "중급"),
    q("p5-070", "The candidate's qualifications were more impressive _____ those of the other applicants.", ["as", "than", "to", "like"], 1, "more impressive와 함께 비교 대상을 이끌 때 than을 씁니다.", "비교급", "초급"),
    q("p5-071", "The office manager arranged for the documents _____ by courier.", ["deliver", "delivering", "to be delivered", "delivered"], 2, "arrange for 목적어 to be p.p. 구조로 문서가 배송되도록 했다는 의미입니다.", "부정사 수동", "고급"),
    q("p5-072", "The client was pleased with how _____ the issue was resolved.", ["quick", "quickness", "quickly", "quicken"], 2, "resolved를 수식해야 하므로 부사 quickly가 필요합니다.", "품사", "초급"),
    q("p5-073", "The company is seeking ways to reduce energy _____.", ["consume", "consumed", "consumption", "consuming"], 2, "reduce의 목적어로 에너지 소비를 뜻하는 명사 consumption이 맞습니다.", "어휘", "중급"),
    q("p5-074", "The manager reminded staff _____ all confidential files before leaving.", ["lock", "to lock", "locking", "locked"], 1, "remind 목적어 to do 구조이므로 to lock이 정답입니다.", "부정사", "초급"),
    q("p5-075", "The warranty covers defects _____ from normal use of the product.", ["result", "resulted", "resulting", "results"], 2, "defects를 뒤에서 수식하는 현재분사 resulting이 필요합니다.", "분사", "고급"),
    q("p5-076", "The two departments have worked together _____ the beginning of the project.", ["since", "during", "by", "within"], 0, "현재완료와 시작 시점 the beginning이 함께 쓰였으므로 since가 맞습니다.", "전치사", "초급"),
    q("p5-077", "The sales representative spoke _____ about the product's features.", ["confidence", "confident", "confidently", "confidential"], 2, "spoke를 수식해야 하므로 부사 confidently가 필요합니다.", "품사", "초급"),
    q("p5-078", "The conference organizer provided attendees with _____ information about nearby hotels.", ["detail", "detailed", "detailing", "details"], 1, "information을 수식하는 형용사 detailed가 맞습니다.", "품사", "초급"),
    q("p5-079", "The restaurant will remain closed on Monday _____ renovations are completed.", ["while", "whether", "unless", "whereas"], 0, "공사가 진행되는 동안 닫혀 있다는 시간 관계이므로 while이 자연스럽습니다.", "접속사", "중급"),
    q("p5-080", "The new employee completed the orientation program _____ than expected.", ["soon", "sooner", "soonest", "soonly"], 1, "than expected가 있으므로 비교급 sooner가 필요합니다.", "비교급", "초급")
];

function q(id, sentence, choices, answerIndex, explanation, grammarPoint, difficulty) {
    return {
        id: id,
        sentence: sentence,
        choices: choices,
        answerIndex: answerIndex,
        explanation: explanation,
        grammarPoint: grammarPoint,
        difficulty: difficulty
    };
}

